name: Build and Release XCFramework

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Get Tag Info
        id: taginfo
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            DATE=$(date +"%d-%m-%Y")
            TIMESTAMP=$(date +%s)
            TAG="$DATE-$TIMESTAMP"
            echo "TAG=$TAG" >> $GITHUB_ENV
            echo "tag=$TAG" >> $GITHUB_OUTPUT
           else
            # Manual trigger fallback (e.g., set version manually)
            echo "TAG=manual-release" >> $GITHUB_ENV
            echo "tag=manual-release" >> $GITHUB_OUTPUT
          fi

      - name: Build XCFramework
        run: |
          cd TesseractOCR/
          make

      - name: Zip XCFramework
        run: |
          cd TesseractOCR/
          zip -r TesseractOCR.xcframework.zip xcframework/TesseractOCR.xcframework
          cd ..
      - name: Create Git Tag (if push to main)
        if: github.event_name == 'push'
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag $TAG
            git push origin $TAG

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.taginfo.outputs.tag }}
          release_name: Release ${{ steps.taginfo.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./YourLibrary.xcframework.zip
          asset_name: YourLibrary.xcframework.zip
          asset_content_type: application/zip
